# NumPy

## Table of Contents
- [NumPy Arrays](#NumPy-Arrays)
    - [i. Creating NumPy Arrays](#i.-Creating-NumPy-Arrays)
    - [ii. Arrays Attributes and Methods](#ii.-Arrays-Attributes-and-Methods)
    - [iii. NumPy Indexing and Selection](#iii.-NumPy-Indexing-and-Selection)
    - [iv. NumPy Operations](#iv.-NumPy-Operations)


[References](#References)

In [1]:
import numpy as np

### NumPy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (Note: A matrix can still have only one row or one column).

### i. Creating NumPy Arrays

**From a Python List**

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)
# Note the double [[]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**From Build-in Methods**

- arange

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

- zeros and ones

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- linspace

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

- eye

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**random**

- rand
    
  Create an array of the given shape and populate it with random samples from a uniform distribution over `[0, 1)`.

In [13]:
np.random.rand(2)

array([0.30014212, 0.00160733])

In [14]:
np.random.rand(5,5)

array([[0.70553604, 0.06370946, 0.10654489, 0.65219327, 0.26216116],
       [0.94256096, 0.86302484, 0.38199786, 0.79059493, 0.54190754],
       [0.29744632, 0.54139381, 0.2202058 , 0.55567993, 0.57897575],
       [0.59104589, 0.95036405, 0.31069309, 0.03440959, 0.32036628],
       [0.79698225, 0.80900689, 0.00624519, 0.39519484, 0.64239027]])

- randn
  
  Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [15]:
np.random.randn(2)

array([-0.15031575, -0.02081116])

In [16]:
np.random.randn(5,5)

array([[-0.22030078, -0.33803991,  0.48302303, -0.69883272,  0.90794232],
       [ 1.79058626,  1.59413116, -0.35856493,  0.49146488,  0.49384663],
       [ 1.7283127 , -0.60029822,  0.61312798, -0.85163958, -1.45948753],
       [-0.02888799,  0.0834585 ,  1.24773915,  0.13288667,  2.37333164],
       [ 0.22615364,  0.69123882,  0.42825455,  1.29576275,  0.51218581]])

- randint

  Return random integers from `low` (inclusive) to `high` (exclusive).

In [17]:
np.random.randint(1,100)

90

In [18]:
np.random.randint(1,100,10)

array([96,  2, 31, 87, 96, 51, 71, 97, 39,  6])

Return to [Table of Contents](#Table-of-Contents)

### ii. Arrays Attributes and Methods

In [19]:
# Set up
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

**dtype**

Shows the data type of the object in the array.

In [20]:
arr.dtype

dtype('int64')

**Shape**

Shows the shape of the array. Shape is an attribute, not a method.

In [21]:
arr.shape

(25,)

**Reshape**

Returns an array containing the same data with a new shape.

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max, min, argmax, argmin**

In [24]:
ranarr

array([11, 19, 15,  8, 20, 25, 26, 20, 15, 11])

In [25]:
ranarr.max() # Max value

26

In [26]:
ranarr.argmax() # Index of max value

6

In [27]:
ranarr.min()

8

In [28]:
ranarr.argmin()

3

Return to [Table of Contents](#Table-of-Contents)

### iii. NumPy Indexing and Selection

In [29]:
# Set up
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Bracket Indexing and Selection**

In [30]:
# Get a value at an index
arr[8]

8

In [31]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

**Broadcasting**

Numpy arrays differ from a normal Python list because of their ability to broadcast.

In [32]:
arr = np.arange(0,11)

# Setting a value with index range (Broadcasting)
arr[:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

> Important Note on Slices

**Any changes to a slice of the array will also occur in the original array.**

This is because the slice of the array is actually **a view of the original array and not a new copy**. It is designed as such to avoid memory problems with large arrays.

To get a copy of the array, it needs to be explicit stated, i.e. `arr_copy = arr.copy()`.

As Pandas is built upon NumPy, Pandas behaves in the same way too.

In [33]:
# Reset array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
slice_of_arr = arr[0:6] # Creating slice of array
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [35]:
slice_of_arr[:] = 99 # Change slice thru broadcasting
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [36]:
arr # Note that the original array is being changed by the broadcasting too

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Indexing a 2D Array (Matrices)**

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. For clarity, the comma notation is recommended.

In [37]:
# Set up
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [39]:
# Getting individual element value
arr_2d[1,0]

20

In [40]:
# 2D array slicing

# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

**Conditional Selection**

In [41]:
# Set up
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

Return to [Table of Contents](#Table-of-Contents)

### iv. NumPy Operations

**Array with Array**

In [44]:
# Set up
arr = np.arange(0,10)

In [45]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [48]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

<ipython-input-48-26a5e16254a4>:3: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [49]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-49-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

**Array with Scalar**

In [50]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [51]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

**Universal Array Functions**

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially mathematical operations that can used to perform the operation across the array. Some common ones are shown below.

In [52]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
np.max(arr) # Same as arr.max()

9

In [55]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [56]:
np.log(arr)

<ipython-input-56-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### References

- Jose Portilla. Python for Data Science and Machine Learning Bootcamp.

Return to [Table of Contents](#Table-of-Contents)